### PR TITLE
Rebrand from fatd to pegnetd

### PR DESCRIPTION
**Pull request by sambarnes**

### CODE REVIEW

**Review by sanchopansa — COMMENTED** [review]
Thanks, Sam! LGTM, aside from one small suggestion: I think we should drop "pegnet" from the method names in the `PegNetd` class, e.g. "get_pegnet_balances" -> "get_balances", etc.

**Comment by sambarnes** [comment]
Yeah I think I agree with that. Originally I did drop them, however, then I got to thinking that in the future when pegnet-py and fatpy merge, then it'll be an easier transition for people that use pegnet-py already. So there won't be confusion between a FAT-0/1 endpoint and a colliding pegnet one

Thoughts? Maybe since pegnet-py will be deprecated and they'll have to change code anyways, we should just drop the pegnet part though.

**Comment by sanchopansa** [comment]
Hmm, good question. The way I imagine it working is that `fat-py` will expose a different module (e.g. fat2), which you could use for PegNet related stuff and potentially other projects that follow the same standard. So, if `fat-py` does that I would expect that there is a generic `get_balances` method, which works for PegNet and other applications following the same standard (potentially providing some auxiliary information as input parameters to the function).

So, I think overall I'm leaning towards dropping the `pegnet` part from the methods.

Let me know what you think.

**Comment by sambarnes** [comment]
I agree with that. Dropping them now

**Review by sanchopansa — APPROVED** [review]

**Pull request merged**
